services:
    lmdi.delre.listener:
        class: lmdi\hidebots\event\listener
        arguments:
            - @controller.helper
            - @template
            - @dbal.conn
        tags:
            - { name: event.listener }
